// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const firebaseConfig = <String, String>{
    'apiKey': 'AIzaSyBoaT2wqgyZ_oYeUSGnqEvMGaGT3tiX0c4',
    'authDomain': 'lifemate-bb8c2.firebaseapp.com',
    'databaseURL': 'https://lifemate-bb8c2-default-rtdb.firebaseio.com',
    'projectId': 'lifemate-bb8c2',
    'storageBucket': 'lifemate-bb8c2.firebasestorage.app',
    'messagingSenderId': '551555315932',
    'appId': '1:551555315932:web:3d2a638762cfea3dc6dc19',
    'measurementId': 'G-HRDPKT8QKH',
  };

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoaT2wqgyZ_oYeUSGnqEvMGaGT3tiX0c4',
    appId: '1:551555315932:web:3d2a638762cfea3dc6dc19',
    messagingSenderId: '551555315932',
    projectId: 'lifemate-bb8c2',
    authDomain: 'lifemate-bb8c2.firebaseapp.com',
    databaseURL: 'https://lifemate-bb8c2-default-rtdb.firebaseio.com',
    storageBucket: 'lifemate-bb8c2.firebasestorage.app',
    measurementId: 'G-HRDPKT8QKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1a2FNOvaQ5OAA_GHWLHSNNGoJu1mqwQ',
    appId: '1:551555315932:android:8b7c9370efec2179c6dc19',
    messagingSenderId: '551555315932',
    projectId: 'lifemate-bb8c2',
    databaseURL: 'https://lifemate-bb8c2-default-rtdb.firebaseio.com',
    storageBucket: 'lifemate-bb8c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CjZ6HoIoCJm5Wq6H2dytxBwx0iIgxNg',
    appId: '1:551555315932:ios:e36248a6f3befa90c6dc19',
    messagingSenderId: '551555315932',
    projectId: 'lifemate-bb8c2',
    databaseURL: 'https://lifemate-bb8c2-default-rtdb.firebaseio.com',
    storageBucket: 'lifemate-bb8c2.firebasestorage.app',
    iosBundleId: 'com.example.lifemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoaT2wqgyZ_oYeUSGnqEvMGaGT3tiX0c4',
    appId: '1:551555315932:web:3d2a638762cfea3dc6dc19',
    messagingSenderId: '551555315932',
    projectId: 'lifemate-bb8c2',
    authDomain: 'lifemate-bb8c2.firebaseapp.com',
    databaseURL: 'https://lifemate-bb8c2-default-rtdb.firebaseio.com',
    storageBucket: 'lifemate-bb8c2.firebasestorage.app',
    measurementId: 'G-HRDPKT8QKH',
  );
}
